services:
  - type: web
    name: pneumonia-detection
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: waitress-serve --port=$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
